In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran"],
    "Age": [24, 25, 23, 26, 24],
    "Marks": [85, 92, 76, 88, 95],
    "Branch": ["CSE", "ECE", "CSE", "ECE", "CSE"]
})
df

    Name  Age  Marks Branch
0   Ravi   24     85    CSE
1  Priya   25     92    ECE
2   Arun   23     76    CSE
3   Sita   26     88    ECE
4  Kiran   24     95    CSE

# 1. index

In [3]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)

can also create a custom index

In [5]:
df.index = ["S1", "S2", "S3", "S4", "S5"]
df

     Name  Age  Marks Branch
S1   Ravi   24     85    CSE
S2  Priya   25     92    ECE
S3   Arun   23     76    CSE
S4   Sita   26     88    ECE
S5  Kiran   24     95    CSE

# 2. columns

In [12]:
print(df.columns)
df.columns

Index(['Name', 'Age', 'Marks', 'Branch'], dtype='str')

Index(['Name', 'Age', 'Marks', 'Branch'], dtype='str')

In [11]:
df.columns.tolist()

['Name', 'Age', 'Marks', 'Branch']

# 6. dtypes
- Unlike a Series, a DataFrame can contain different data types in different columns.

In [14]:
df.dtypes

Name        str
Age       int64
Marks     int64
Branch      str
dtype: object

# 7. values

In [23]:
df.values

array([['Ravi', 24, 85, 'CSE'],
       ['Priya', 25, 92, 'ECE'],
       ['Arun', 23, 76, 'CSE'],
       ['Sita', 26, 88, 'ECE'],
       ['Kiran', 24, 95, 'CSE']], dtype=object)

In [24]:
df.values.tolist

In [25]:
df.values.tolist()

[['Ravi', 24, 85, 'CSE'],
 ['Priya', 25, 92, 'ECE'],
 ['Arun', 23, 76, 'CSE'],
 ['Sita', 26, 88, 'ECE'],
 ['Kiran', 24, 95, 'CSE']]

In [27]:
print(type(df.values))

<class 'numpy.ndarray'>

# pandas to numpy

In [28]:
import numpy as np

In [29]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 25, 30],
    "Marks": [85, 90, 95]
})

df

      Name  Age  Marks
0    Alice   20     85
1      Bob   25     90
2  Charlie   30     95

In [31]:
array = df.to_numpy()
print(array)

[['Alice' 20 85]
 ['Bob' 25 90]
 ['Charlie' 30 95]]

# Why convert DataFrame to NumPy?
```
Pandas and NumPy are designed for slightly different purposes.

Pandas
Good for working with structured/tabular data:
df["Age"]
df["Marks"]
df[df["Marks"] > 90]

NumPy
Good for numerical computation and arrays:
array.mean()
array.shape
array[0, 1]

For example, if you have a machine-learning algorithm that expects a NumPy array, you might convert:

X = df.to_numpy()

```