In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran"],
    "Age": [24, 25, 23, 26, 24],
    "Marks": [85, 92, 76, 88, 95],
    "Branch": ["CSE", "ECE", "CSE", "ECE", "CSE"]
})

# DataFrame Information
- Properties tell you basic structural information.
```
info()
describe()
head()
tail()
memory_usage()
count()

```

### **1. info()**
info() gives you a compact overview of the DataFrame.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   Branch  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

### **2. describe()**
describe() generates descriptive statistics for numerical columns by default.

In [7]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   24.400000  87.200000
std     1.140175   7.328028
min    23.000000  76.000000
25%    24.000000  85.000000
50%    24.000000  88.000000
75%    25.000000  92.000000
max    26.000000  95.000000

In [8]:
df.describe

<bound method NDFrame.describe of     Name  Age  Marks Branch
0   Ravi   24     85    CSE
1  Priya   25     92    ECE
2   Arun   23     76    CSE
3   Sita   26     88    ECE
4  Kiran   24     95    CSE>

In [9]:
df.describe(include="all")

        Name        Age      Marks Branch
count      5   5.000000   5.000000      5
unique     5        NaN        NaN      2
top     Ravi        NaN        NaN    CSE
freq       1        NaN        NaN      3
mean     NaN  24.400000  87.200000    NaN
std      NaN   1.140175   7.328028    NaN
min      NaN  23.000000  76.000000    NaN
25%      NaN  24.000000  85.000000    NaN
50%      NaN  24.000000  88.000000    NaN
75%      NaN  25.000000  92.000000    NaN
max      NaN  26.000000  95.000000    NaN

df.head() and tail

### **5. memory_usage()**
- memory_usage() tells you approximately how much memory each column uses.
- For columns containing strings/objects, `deep=True` tells Pandas to inspect the actual memory consumed by the objects rather than just counting the references.

In [32]:
print(df.memory_usage())
print(df.memory_usage(deep=True))
df.memory_usage(deep=True).sum()

Index     132
Name       40
Age        40
Marks      40
Branch     40
dtype: int64
Index     132
Name      267
Age        40
Marks      40
Branch    260
dtype: int64

np.int64(739)

### **6. count()**
count() returns the number of non-missing values.

In [35]:
print(df.count())
df.loc[2, "Marks"] = None
print(df.count())

Name      5
Age       5
Marks     5
Branch    5
dtype: int64
Name      5
Age       5
Marks     4
Branch    5
dtype: int64

In [36]:
df.isnull().sum()

Name      0
Age       0
Marks     1
Branch    0
dtype: int64

In [37]:
df.index

RangeIndex(start=0, stop=5, step=1)