In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran", "Meena"],
    "Age": [24, 25, 23, 26, 24, 29],
    "Salary": [50000, 65000, 55000, 70000, 60000, 80000],
    "Branch": ["CSE", "ECE", np.nan, "ECE", "CSE", "IT"],
    "City": ["Vijayawada", "Hyderabad", "Chennai",
             "Hyderabad", "Vijayawada", "Bangalore"]
})
df

    Name  Age  Salary Branch        City
0   Ravi   24   50000    CSE  Vijayawada
1  Priya   25   65000    ECE   Hyderabad
2   Arun   23   55000    NaN     Chennai
3   Sita   26   70000    ECE   Hyderabad
4  Kiran   24   60000    CSE  Vijayawada
5  Meena   29   80000     IT   Bangalore

### **1. Filtering Rows**

In [3]:
df[df["Age"] > 25]

    Name  Age  Salary Branch       City
3   Sita   26   70000    ECE  Hyderabad
5  Meena   29   80000     IT  Bangalore

In [4]:
df[df["Salary"] > 60000]

    Name  Age  Salary Branch       City
1  Priya   25   65000    ECE  Hyderabad
3   Sita   26   70000    ECE  Hyderabad
5  Meena   29   80000     IT  Bangalore

### **2. Filtering Columns**

In [5]:
df[["Name", "Salary"]]

    Name  Salary
0   Ravi   50000
1  Priya   65000
2   Arun   55000
3   Sita   70000
4  Kiran   60000
5  Meena   80000

In [6]:
numeric_cols = df.select_dtypes(include="number")
numeric_cols

   Age  Salary
0   24   50000
1   25   65000
2   23   55000
3   26   70000
4   24   60000
5   29   80000

### **Filtering Rows AND Columns**

In [7]:
df.loc[df["Salary"] > 60000, ["Name", "Salary"]]

    Name  Salary
1  Priya   65000
3   Sita   70000
5  Meena   80000

### **3. Filtering Numerical Values**

In [10]:
df[df["Age"] > 25]
df[df["Age"] >= 25]
df[df["Age"] < 25]
df[df["Age"] <= 25]
df[df["Age"] == 25]
df[df["Age"] == 25] / df[~(df["Age"] == 25)]

  Name  Age  Salary Branch City
0  NaN  NaN     NaN    NaN  NaN
1  NaN  NaN     NaN    NaN  NaN
2  NaN  NaN     NaN    NaN  NaN
3  NaN  NaN     NaN    NaN  NaN
4  NaN  NaN     NaN    NaN  NaN
5  NaN  NaN     NaN    NaN  NaN

### **4. Filtering String Values**

In [12]:
df[df["Branch"] == "CSE"]
df[~(df["Branch"] == "CSE")]

    Name  Age  Salary Branch       City
1  Priya   25   65000    ECE  Hyderabad
3   Sita   26   70000    ECE  Hyderabad
5  Meena   29   80000     IT  Bangalore

### **String methods**

In [ ]:
df[df["City"].str.contains("Hyd")]
df[df["Branch"].str.lower() == "cse"]
df[df["Branch"].str.contains("cse", case=False, na=True)]  # na, If the value is missing(Nulls), return False, without it, returns None/null/NaN

    Name  Age  Salary Branch        City
0   Ravi   24   50000    CSE  Vijayawada
2   Arun   23   55000    NaN     Chennai
4  Kiran   24   60000    CSE  Vijayawada

In [15]:
df[df["Name"].str.startswith("R")]
df[df["Name"].str.endswith("a")]

    Name  Age  Salary Branch       City
1  Priya   25   65000    ECE  Hyderabad
3   Sita   26   70000    ECE  Hyderabad
5  Meena   29   80000     IT  Bangalore