In [64]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran", "Meena"],
    "Age": [24, 25, 23, 26, 24, 29],
    "Salary": [50000, 65000, 55000, 70000, 60000, 80000],
    "Branch": ["CSE", "ECE", "CSE", "ECE", "CSE", "IT"],
    "City": ["Vijayawada", "Hyderabad", "Chennai",
             "Hyderabad", "Vijayawada", "Bangalore"]
})
df

    Name  Age  Salary Branch        City
0   Ravi   24   50000    CSE  Vijayawada
1  Priya   25   65000    ECE   Hyderabad
2   Arun   23   55000    CSE     Chennai
3   Sita   26   70000    ECE   Hyderabad
4  Kiran   24   60000    CSE  Vijayawada
5  Meena   29   80000     IT   Bangalore

### **1. isin()**

In [65]:
df[df["Branch"].isin(["CSE", "ECE"])]
df[df["Age"].isin([22,23,25,29])]

    Name  Age  Salary Branch       City
1  Priya   25   65000    ECE  Hyderabad
2   Arun   23   55000    CSE    Chennai
5  Meena   29   80000     IT  Bangalore

### **2. between()**

In [66]:
df[df["Salary"].between(60000, 70000)]
df[df["Salary"].between(60000, 70000, inclusive="neither")]
# 60000 → excluded
# 70000 → excluded

    Name  Age  Salary Branch       City
1  Priya   25   65000    ECE  Hyderabad

### **3. query()**

In [67]:
df[(df["Salary"] > 60000) & (df["Age"] > 25)]
df.query("Age > 25 and Salary > 60000")

    Name  Age  Salary Branch       City
3   Sita   26   70000    ECE  Hyderabad
5  Meena   29   80000     IT  Bangalore

### **Using Python variables with query()**

In [68]:
min_sal = 60000
df.query("Salary >= @min_sal")

    Name  Age  Salary Branch        City
1  Priya   25   65000    ECE   Hyderabad
3   Sita   26   70000    ECE   Hyderabad
4  Kiran   24   60000    CSE  Vijayawada
5  Meena   29   80000     IT   Bangalore

### **4. filter()**

DataFrame.filter() is primarily used to select labels, usually columns or indexes.

In [69]:
df.filter(items=["Name", "Salary"])

    Name  Salary
0   Ravi   50000
1  Priya   65000
2   Arun   55000
3   Sita   70000
4  Kiran   60000
5  Meena   80000

In [70]:
#  select columns containing "Score"
df.filter(like="Score")
# the column name ends with "score".
df.filter(regex="score$")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

### **5. Boolean Masks**

In [71]:
age_mask = df["Age"] >= 25
salary_mask = df["Salary"] > 60000
result = df[
    age_mask & salary_mask
]
result

    Name  Age  Salary Branch       City
1  Priya   25   65000    ECE  Hyderabad
3   Sita   26   70000    ECE  Hyderabad
5  Meena   29   80000     IT  Bangalore

### **6. Conditional Filtering with loc[]**
df.loc[condition, columns]

In [72]:
df.loc[df["Salary"] > 60000, ["Name", "Salary"]]

    Name  Salary
1  Priya   65000
3   Sita   70000
5  Meena   80000

In [73]:
# Give everyone with salary below ₹60,000 a 10% raise
df.loc[df["Salary"] < 60000, "Salary"] = (
    df.loc[df["Salary"] < 60000, "Salary"] * 1.10
).astype(int)

# or

# df["Salary"] = df["Salary"].astype(float)
# df.loc[df["Salary"] < 60000, "Salary"] *= 1.10

# int64 column
#    ↓
# float64 values
#    ↓
# TypeError
df

    Name  Age  Salary Branch        City
0   Ravi   24   55000    CSE  Vijayawada
1  Priya   25   65000    ECE   Hyderabad
2   Arun   23   60500    CSE     Chennai
3   Sita   26   70000    ECE   Hyderabad
4  Kiran   24   60000    CSE  Vijayawada
5  Meena   29   80000     IT   Bangalore

In [83]:
df.loc[
    (df["Branch"].isin(["CSE", "ECE"])) &
    (df["Age"].between(24, 26)) &
    (df["Salary"] >= 55000),
    ["Name", "Age", "Salary", "City"]
]
df.query(
    "Branch in ['CSE', 'ECE'] and "
    "Age >=24 and Age <= 26 and "
    "Salary >= 55000"
)[
    ["Name", "Age", "Salary", "City"]
]

    Name  Age  Salary        City
0   Ravi   24   55000  Vijayawada
1  Priya   25   65000   Hyderabad
3   Sita   26   70000   Hyderabad
4  Kiran   24   60000  Vijayawada

In [105]:
df = pd.DataFrame({
    "Name": [
        " ravi kumar ",
        "PRIYA SHARMA",
        " Arun Kumar",
        "sita  reddy "
    ]
})

In [106]:
df["Name"] = (
    df["Name"]
    .str.strip()
    # .str.replace(r"\s+", " ", regex=True)
    .str.title()
)
df

           Name
0    Ravi Kumar
1  Priya Sharma
2    Arun Kumar
3   Sita  Reddy

In [98]:
s = pd.Series([
    "hello world",
    "machine learning",
    "python"
])
s.str.find("o")

0    4
1   -1
2    4
dtype: int64