In [26]:
import pandas as pd
df = pd.DataFrame({
    "Name": [
        "Ravi", "Priya", "Arun",
        "Sita", "Kiran", "Meena"
    ],
    "Department": [
        "IT", "HR", "IT",
        "HR", "IT", "Sales"
    ],
    "Salary": [
        50000, 60000, 55000,
        70000, 65000, 80000
    ],
    "Experience": [
        2, 4, 3, 6, 5, 7
    ]
})
df

    Name Department  Salary  Experience
0   Ravi         IT   50000           2
1  Priya         HR   60000           4
2   Arun         IT   55000           3
3   Sita         HR   70000           6
4  Kiran         IT   65000           5
5  Meena      Sales   80000           7

In [27]:
result = df.groupby("Department")["Salary"].mean().reset_index()
result

  Department        Salary
0         HR  65000.000000
1         IT  56666.666667
2      Sales  80000.000000

In [28]:
# df
df.groupby("Department")["Salary"].agg(
    ["mean", "max", "min"]
).reset_index()

  Department          mean    max    min
0         HR  65000.000000  70000  60000
1         IT  56666.666667  65000  50000
2      Sales  80000.000000  80000  80000

In [29]:
df = pd.DataFrame({
    "Region": [
        "South", "South", "North",
        "North", "South", "North"
    ],
    "Product": [
        "Laptop", "Phone", "Laptop",
        "Phone", "Laptop", "Laptop"
    ],
    "Sales": [
        100000, 50000, 120000,
        60000, 90000, 110000
    ]
})
# 	What are the total sales for each product in each region?

In [30]:
df.groupby(["Region", "Product"])["Sales"].sum().reset_index()

  Region Product   Sales
0  North  Laptop  230000
1  North   Phone   60000
2  South  Laptop  190000
3  South   Phone   50000

In [33]:
df1 = pd.DataFrame({
    "Name": ["Ravi", "Priya"],
    "Age": [24, 25],
    "Salary": [50000, 60000]
})
df2 = pd.DataFrame({
    "Name": ["Ravi", "Priya"],
    "Salary": [50000, 60000]
})

In [41]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita"],
    "Age": [24, None, 23, 26],
    "Salary": [50000, 65000, None, 70000]
})
df.isna()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False