In [17]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran", "Meena", "Siva"],
    "Branch": ["CSE", "ECE", "CSE", "ECE", "CSE", "IT", "CSE"],
    "Age": [24, 25, 23, 26, 24, 29, 28],
    "Marks": [78, 92, 85, 92, 67, 88, 92],
    "Salary": [50000, 65000, 55000, 70000, 60000, 80000, 900000]
})

### **1. sort_values()**
Sorting doesn't normally change the original DataFrame

sorts based on column values

```ruby
df.sort_values(
    by="column_name"
    axis=0,
    ascending=True,
    inplace=False,
    kind="quicksort",
    na_position="last",
    ignore_index=False,
    key=None
)

In [18]:
df.sort_values(by="Marks", ascending=False, inplace=False)

    Name Branch  Age  Marks  Salary
1  Priya    ECE   25     92   65000
6   Siva    CSE   28     92  900000
3   Sita    ECE   26     92   70000
5  Meena     IT   29     88   80000
2   Arun    CSE   23     85   55000
0   Ravi    CSE   24     78   50000
4  Kiran    CSE   24     67   60000

In [20]:
df.sort_values(by=['Marks', 'Branch'], ascending=[False, True])

    Name Branch  Age  Marks  Salary
6   Siva    CSE   28     92  900000
1  Priya    ECE   25     92   65000
3   Sita    ECE   26     92   70000
5  Meena     IT   29     88   80000
2   Arun    CSE   23     85   55000
0   Ravi    CSE   24     78   50000
4  Kiran    CSE   24     67   60000

## **key**

key allows you to transform the values before sorting.

In [25]:
df = pd.DataFrame({
    "Name": ["ravi", "PRIYA", "arun", "SNEHA"]
})
df

    Name
0   ravi
1  PRIYA
2   arun
3  SNEHA

In [26]:
df.sort_values(
    by="Name",
    key=lambda x: x.str.lower()
)

    Name
2   arun
1  PRIYA
0   ravi
3  SNEHA

### **Sorting by Index**
sorts based on the index labels

```ruby
df.sort_index(
    axis=0,
    level=None,
    ascending=True,
    inplace=False,
    kind="quicksort",
    na_position="last",
    sort_remaining=True,
    ignore_index=False,
    key=None
)
```

In [21]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sneha"],
    "Age": [28, 22, 25, 30],
    "Salary": [50000, 70000, 45000, 60000]
}, index=["D", "B", "A", "C"])
df

    Name  Age  Salary
D   Ravi   28   50000
B  Priya   22   70000
A   Arun   25   45000
C  Sneha   30   60000

### **axis**
- axis=0 → row index
- axis=1 → column index

In [24]:
df.sort_index(axis=0)

    Name  Age  Salary
A   Arun   25   45000
B  Priya   22   70000
C  Sneha   30   60000
D   Ravi   28   50000

## **NaN**

In [28]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun"],
    "Age": [28, 22, 25]
}, index=["B", None, "A"])

In [32]:
df.sort_index(na_position="first")

      Name  Age
NaN  Priya   22
A     Arun   25
B     Ravi   28

### **ignore_index**
ignore_index=False → keep index labels

ignore_index=True  → reset to 0, 1, 2...

In [34]:
df.sort_index(ignore_index=True)

    Name  Age
0   Arun   25
1   Ravi   28
2  Priya   22

### **level**
MultiIndex

In [ ]:
df = pd.DataFrame({
    "Salary": [50000, 60000, 70000, 80000]
}, index=pd.MultiIndex.from_tuples([
    ("CSE", "Ravi"),
    ("ECE", "Priya"),
    ("CSE", "Arun"),
    ("ECE", "Sneha")
], names=["Branch", "Name"]))