In [1]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran", "Meena"],
    "Branch": ["CSE", "ECE", "CSE", "ECE", "CSE", "IT"],
    "Age": [24, 25, 23, 26, 24, 29],
    "Marks": [78, 92, 85, 92, 67, 88],
    "Salary": [50000, 65000, 55000, 70000, 60000, 80000]
})
df

    Name Branch  Age  Marks  Salary
0   Ravi    CSE   24     78   50000
1  Priya    ECE   25     92   65000
2   Arun    CSE   23     85   55000
3   Sita    ECE   26     92   70000
4  Kiran    CSE   24     67   60000
5  Meena     IT   29     88   80000

In [3]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sneha"],
    "Salary": [50000, 70000, 45000, 60000]
})
df

    Name  Salary
0   Ravi   50000
1  Priya   70000
2   Arun   45000
3  Sneha   60000

```ruby
Series.rank(
    axis=0,
    method="average",
    numeric_only=False,
    na_option="keep",
    ascending=True,
    pct=False
)

In [6]:
df["Salary"].rank()

0    2.0
1    4.0
2    1.0
3    3.0
Name: Salary, dtype: float64

### **ascending**
This controls whether the smallest or largest value gets rank 1.

In [8]:
df["Salary"].rank(ascending=False)

0    3.0
1    1.0
2    4.0
3    2.0
Name: Salary, dtype: float64

### **3. method**
It decides what happens when two or more values are tied.

`method="average"` — default

In [10]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sneha"],
    "Salary": [50000, 70000, 50000, 60000]
})

In [ ]:
# avg rank  
df["Salary"].rank()

0    1.5
1    4.0
2    1.5
3    3.0
Name: Salary, dtype: float64

In [15]:
df["Salary"].rank(method="min")
df["Salary"].rank(method="max")
# This gives ranks based on the order in which the values appear.
df["Salary"].rank(method="first")
# Tied values get the same rank, but the next rank doesn't skip.
df["Salary"].rank(method='dense')

0    1.0
1    3.0
2    1.0
3    2.0
Name: Salary, dtype: float64

In [17]:
df = pd.DataFrame({
    "Math": [80, 90, 70],
    "Science": [70, 85, 95]
})
df.rank(axis=1)

   Math  Science
0   2.0      1.0
1   2.0      1.0
2   1.0      2.0