In [41]:
import pandas as pd
employees = pd.DataFrame({
    "Name": [
        "Ravi", "Priya", "Arun",
        "Sita", "Kiran", "Meena"
    ],
    "Department": [
        "Engineering", "HR", "Engineering",
        "HR", "Engineering", "Sales"
    ],
    "Experience": [
        3, 5, 2, 7, 4, 6
    ],
    "Salary": [
        60000, 70000, 55000,
        90000, 65000, 85000
    ],
    "Performance": [
        82, 91, 75, 95, 88, 90
    ]
})
employees

    Name   Department  Experience  Salary  Performance
0   Ravi  Engineering           3   60000           82
1  Priya           HR           5   70000           91
2   Arun  Engineering           2   55000           75
3   Sita           HR           7   90000           95
4  Kiran  Engineering           4   65000           88
5  Meena        Sales           6   85000           90

In [42]:
# Highest salary first
employees.nlargest(1, "Salary")
employees.sort_values(by="Salary", ascending=False)

    Name   Department  Experience  Salary  Performance
3   Sita           HR           7   90000           95
5  Meena        Sales           6   85000           90
1  Priya           HR           5   70000           91
4  Kiran  Engineering           4   65000           88
0   Ravi  Engineering           3   60000           82
2   Arun  Engineering           2   55000           75

In [43]:
# Highest performance first
employees.sort_values(by="Performance", ascending=False)

    Name   Department  Experience  Salary  Performance
3   Sita           HR           7   90000           95
1  Priya           HR           5   70000           91
5  Meena        Sales           6   85000           90
4  Kiran  Engineering           4   65000           88
0   Ravi  Engineering           3   60000           82
2   Arun  Engineering           2   55000           75

In [44]:
# Top 3 performers
employees.nlargest(3, "Performance")

    Name Department  Experience  Salary  Performance
3   Sita         HR           7   90000           95
1  Priya         HR           5   70000           91
5  Meena      Sales           6   85000           90

In [45]:
# Lowest 3 salaries
employees.nsmallest(3, "Salary")

    Name   Department  Experience  Salary  Performance
2   Arun  Engineering           2   55000           75
0   Ravi  Engineering           3   60000           82
4  Kiran  Engineering           4   65000           88

In [46]:
# Rank employees by performance
employees["Performance_Rank"] = employees["Performance"].rank(ascending=False).astype(int)
employees

    Name   Department  Experience  Salary  Performance  Performance_Rank
0   Ravi  Engineering           3   60000           82                 5
1  Priya           HR           5   70000           91                 2
2   Arun  Engineering           2   55000           75                 6
3   Sita           HR           7   90000           95                 1
4  Kiran  Engineering           4   65000           88                 4
5  Meena        Sales           6   85000           90                 3

In [47]:
# Rank within department
employees["Department_Rank"] = (
    employees
    .groupby("Department")["Performance"]
    .rank(ascending=False)
    .astype(int)
)
employees

,Name,Department,Experience,Salary,Performance,Performance_Rank,Department_Rank
0,Ravi,Engineering,3,60000,82,5,2
1,Priya,HR,5,70000,91,2,2
2,Arun,Engineering,2,55000,75,6,3
3,Sita,HR,7,90000,95,1,1
4,Kiran,Engineering,4,65000,88,4,1
5,Meena,Sales,6,85000,90,3,1

In [56]:
# Find top employee in each department
sorted_department = ( employees
    .sort_values(["Department", "Performance"], ascending=[True, False])
)
sorted_department

,Name,Department,Experience,Salary,Performance,Performance_Rank,Department_Rank
4,Kiran,Engineering,4,65000,88,4,1
0,Ravi,Engineering,3,60000,82,5,2
2,Arun,Engineering,2,55000,75,6,3
3,Sita,HR,7,90000,95,1,1
1,Priya,HR,5,70000,91,2,2
5,Meena,Sales,6,85000,90,3,1

In [58]:
top_per_department = ( sorted_department
    .groupby("Department")
    .head(1)
)
top_per_department

,Name,Department,Experience,Salary,Performance,Performance_Rank,Department_Rank
4,Kiran,Engineering,4,65000,88,4,1
3,Sita,HR,7,90000,95,1,1
5,Meena,Sales,6,85000,90,3,1

In [ ]:
# Sorting + Ranking Together
leaderboard = employees.copy()
leaderboard = ( leaderboard
    .sort_values(by="Performance", ascending=False)
)
leaderboard
# first rank it. then sort with that rank column

,Name,Department,Experience,Salary,Performance,Performance_Rank,Department_Rank
3,Sita,HR,7,90000,95,1,1
1,Priya,HR,5,70000,91,2,2
5,Meena,Sales,6,85000,90,3,1
4,Kiran,Engineering,4,65000,88,4,1
0,Ravi,Engineering,3,60000,82,5,2
2,Arun,Engineering,2,55000,75,6,3