In [30]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita"],
    "Age": [24, 25, 23, 26],
    "Salary": [50000, 65000, 55000, 70000],
    "Branch": ["CSE", "ECE", "CSE", "ECE"]
})
print(df)

    Name  Age  Salary Branch
0   Ravi   24   50000    CSE
1  Priya   25   65000    ECE
2   Arun   23   55000    CSE
3   Sita   26   70000    ECE

# Columns

In [31]:
df["Experience"] = [1, 3, 2, 4]
df

    Name  Age  Salary Branch  Experience
0   Ravi   24   50000    CSE           1
1  Priya   25   65000    ECE           3
2   Arun   23   55000    CSE           2
3   Sita   26   70000    ECE           4

In [32]:
df["Country"] = "India"
df

    Name  Age  Salary Branch  Experience Country
0   Ravi   24   50000    CSE           1   India
1  Priya   25   65000    ECE           3   India
2   Arun   23   55000    CSE           2   India
3   Sita   26   70000    ECE           4   India

In [36]:
df["Annual_Salary"] = df["Salary"] * 12
df

    Name  Age  Salary Branch  Experience Country  Annual_Salary
0   Ravi   24   50000    CSE         1.0   India         600000
1  Priya   25   65000    ECE         3.0   India         780000
2   Arun   23   55000    CSE         2.0   India         660000
3   Sita   26   70000    ECE         4.0   India         840000
4  Kiran   24   60000    CSE         NaN     NaN         720000
5  Kiran   24   60000    CSE         NaN     NaN         720000
6  Meena   27   75000    ECE         NaN     NaN         900000

In [37]:
df["Age_Group"] = df["Age"].apply(
    lambda age: "Young" if age < 25 else "Adult"
)
df

    Name  Age  Salary Branch  Experience Country  Annual_Salary Age_Group
0   Ravi   24   50000    CSE         1.0   India         600000     Young
1  Priya   25   65000    ECE         3.0   India         780000     Adult
2   Arun   23   55000    CSE         2.0   India         660000     Young
3   Sita   26   70000    ECE         4.0   India         840000     Adult
4  Kiran   24   60000    CSE         NaN     NaN         720000     Young
5  Kiran   24   60000    CSE         NaN     NaN         720000     Young
6  Meena   27   75000    ECE         NaN     NaN         900000     Adult

In [39]:
df["Salary_per_Age"] = (
    df["Salary"] / df["Age"]
)
df

,Name,Age,Salary,Branch,Experience,Country,Annual_Salary,Age_Group,Salary_per_Age
0,Ravi,24,50000,CSE,1.0,India,600000,Young,2083.333333
1,Priya,25,65000,ECE,3.0,India,780000,Adult,2600.000000
2,Arun,23,55000,CSE,2.0,India,660000,Young,2391.304348
3,Sita,26,70000,ECE,4.0,India,840000,Adult,2692.307692
4,Kiran,24,60000,CSE,NaN,NaN,720000,Young,2500.000000
5,Kiran,24,60000,CSE,NaN,NaN,720000,Young,2500.000000
6,Meena,27,75000,ECE,NaN,NaN,900000,Adult,2777.777778

## assign()

In [40]:
df = df.assign(
    Annual_Salary=df["Salary"] * 12,
    Salary_Lakhs=df["Salary"] / 100000
)
df

,Name,Age,Salary,Branch,Experience,Country,Annual_Salary,Age_Group,Salary_per_Age,Salary_Lakhs
0,Ravi,24,50000,CSE,1.0,India,600000,Young,2083.333333,0.50
1,Priya,25,65000,ECE,3.0,India,780000,Adult,2600.000000,0.65
2,Arun,23,55000,CSE,2.0,India,660000,Young,2391.304348,0.55
3,Sita,26,70000,ECE,4.0,India,840000,Adult,2692.307692,0.70
4,Kiran,24,60000,CSE,NaN,NaN,720000,Young,2500.000000,0.60
5,Kiran,24,60000,CSE,NaN,NaN,720000,Young,2500.000000,0.60
6,Meena,27,75000,ECE,NaN,NaN,900000,Adult,2777.777778,0.75

In [ ]:
df = (
    df.assign(
        Annual_Salary=lambda x: x["Salary"] * 12,
        Salary_Lakhs=lambda x: x["Salary"] / 100000
    )
)
df

,Name,Age,Salary,Branch,Experience,Country,Annual_Salary,Age_Group,Salary_per_Age,Salary_Lakhs
0,Ravi,24,50000,CSE,1.0,India,600000,Young,2083.333333,0.50
1,Priya,25,65000,ECE,3.0,India,780000,Adult,2600.000000,0.65
2,Arun,23,55000,CSE,2.0,India,660000,Young,2391.304348,0.55
3,Sita,26,70000,ECE,4.0,India,840000,Adult,2692.307692,0.70
4,Kiran,24,60000,CSE,NaN,NaN,720000,Young,2500.000000,0.60
5,Kiran,24,60000,CSE,NaN,NaN,720000,Young,2500.000000,0.60
6,Meena,27,75000,ECE,NaN,NaN,900000,Adult,2777.777778,0.75

In [33]:
new_row = pd.DataFrame({
    "Name": ["Kiran"],
    "Age": [24],
    "Salary": [60000],
    "Branch": ["CSE"]
})

In [34]:
df = pd.concat([df, new_row], ignore_index=True)
df

    Name  Age  Salary Branch  Experience Country
0   Ravi   24   50000    CSE         1.0   India
1  Priya   25   65000    ECE         3.0   India
2   Arun   23   55000    CSE         2.0   India
3   Sita   26   70000    ECE         4.0   India
4  Kiran   24   60000    CSE         NaN     NaN

In [35]:
new_rows = pd.DataFrame({
    "Name": ["Kiran", "Meena"],
    "Age": [24, 27],
    "Salary": [60000, 75000],
    "Branch": ["CSE", "ECE"]
})
df = pd.concat(
    [df, new_rows],
    ignore_index=True
)
df

    Name  Age  Salary Branch  Experience Country
0   Ravi   24   50000    CSE         1.0   India
1  Priya   25   65000    ECE         3.0   India
2   Arun   23   55000    CSE         2.0   India
3   Sita   26   70000    ECE         4.0   India
4  Kiran   24   60000    CSE         NaN     NaN
5  Kiran   24   60000    CSE         NaN     NaN
6  Meena   27   75000    ECE         NaN     NaN

In [46]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Bob", "Sara"],
    "Age": [20, 30, 22, 40]
})

In [45]:
df["Where_Result"] = df["Age"].where(df["Age"] < 25, "Adult")
df

    Name  Age Where_Result
0   John   20           20
1  Alice   30        Adult
2    Bob   22           22
3   Sara   40        Adult

In [47]:
df["Mask_Result"] = df["Age"].mask(df["Age"] < 25, "Young")
df

    Name  Age Mask_Result
0   John   20       Young
1  Alice   30          30
2    Bob   22       Young
3   Sara   40          40

`where()` → keep when True

`mask()` → replace when True

`np.where()` → choose between two values