In [2]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita"],
    "Age": [24, 25, 23, 26],
    "Salary": [50000, 65000, 55000, 70000],
    "Branch": ["CSE", "ECE", "CSE", "ECE"]
})
df

    Name  Age  Salary Branch
0   Ravi   24   50000    CSE
1  Priya   25   65000    ECE
2   Arun   23   55000    CSE
3   Sita   26   70000    ECE

### **Removing Rows**

In [ ]:
df = df.drop(index=2) # single
df = df.drop(index=[1, 3]) # multi
df = df.drop(index="B") # if custome index
df

    Name  Age  Salary Branch
0   Ravi   24   50000    CSE
1  Priya   25   65000    ECE
3   Sita   26   70000    ECE

In [4]:
df = df.reset_index(drop=True)
df

    Name  Age  Salary Branch
0   Ravi   24   50000    CSE
1  Priya   25   65000    ECE
2   Sita   26   70000    ECE

### **Removing Rows Based on Conditions**
remove people younger than 25

In [ ]:
df = df[df["Age"] >= 25] # prefered
df = df.drop(
    df[df["Age"] < 25].index
)

### **Removing Columns**

In [ ]:
df = df.drop(columns="Branch") # single
df = df.drop(
    columns=["Age", "Branch"] # muti
)

### **Removing Columns**
```
df.drop_duplicates(
    subset=None,
    keep="first",
    inplace=False,
    ignore_index=False
)
```

In [ ]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Ravi", "Arun"],
    "Age": [24, 25, 24, 23],
    "Salary": [50000, 65000, 50000, 55000]
})
df.duplicated() #👉 Find/check duplicates.

0    False
1    False
2     True
3    False
dtype: bool

keep="first" → keep first occurrence (default)

keep="last"  → keep last occurrence

keep=False   → remove every occurrence belonging to a duplicate group

In [ ]:
df = df.drop_duplicates()
df.drop_duplicates(keep="last")
df.drop_duplicates(keep=False)

df = df.reset_index(drop=True)

### **Check duplicates based on one column**

In [ ]:
df.duplicated(subset=["Name"])
df.duplicated(subset=["Name", "Age"])

inplace decides whether pandas changes the original DataFrame or creates a new one.

inplace=False — default

- inplace=False → create/return a changed version
- inplace=True  → change the original

In [ ]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "John"],
    "Age": [20, 25, 20]
})

new_df = df.drop_duplicates()

print(df)
# Original df still contains the duplicate.
df.drop_duplicates(inplace=True)
# Now pandas modifies df itself
df

    Name  Age
0   John   20
1  Alice   25
2   John   20

    Name  Age
0   John   20
1  Alice   25

ignore_index decides what happens to the row index after removing duplicates.

In [11]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "John", "Bob"],
    "Age": [20, 25, 20, 30]
})
df = df.drop_duplicates()
df

    Name  Age
0   John   20
1  Alice   25
3    Bob   30

There is no 2 because that row was deleted.

In [ ]:
df = df.drop_duplicates(ignore_index=True)

ignore_index=False → keep the old index

ignore_index=True  → create a new 0, 1, 2, 3... index