In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("../../../datasets/regression.csv")

print(df.head(5))
print(df.info())

   area  bedrooms  age  location_score   price
0  1200         2   10               7  180000
1  1500         3    5               8  250000
2   900         2   15               6  140000
3  2000         4    3               9  350000
4  1100         2   20               5  150000
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   area            100 non-null    int64
 1   bedrooms        100 non-null    int64
 2   age             100 non-null    int64
 3   location_score  100 non-null    int64
 4   price           100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB
None

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet
)

from sklearn.tree import DecisionTreeRegressor

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    HistGradientBoostingRegressor
)

from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

In [20]:
X = df[["area", "bedrooms", "age", "location_score"]]
y = df["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 3823.040912945688
MSE : 24594895.01210876
RMSE: 4959.324047902976
R2  : 0.996642468078109

In [24]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.1),
    "ElasticNet": ElasticNet(alpha=0.1, l1_ratio=0.5),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "Hist Gradient Boosting": HistGradientBoostingRegressor( random_state=42),
    "SVR": SVR(),
    "KNN": KNeighborsRegressor(n_neighbors=5)
}

results = []

for name, model in models.items():

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse ** 0.5
    r2 = r2_score(y_test, y_pred)

    results.append({
        "Model": name,
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse,
        "R2": r2
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values("R2", ascending=False).reset_index(drop=True)
# results_df.to_csv("regression_results.csv",index=False)
results_df

                    Model           MAE           MSE          RMSE        R2
0           Random Forest   2756.300000  1.060585e+07   3256.662509  0.998552
1       Gradient Boosting   2890.465480  1.362977e+07   3691.852299  0.998139
2       Linear Regression   3823.040913  2.459490e+07   4959.324048  0.996642
3                   Lasso   3823.104119  2.459608e+07   4959.443526  0.996642
4                   Ridge   4245.476426  2.751035e+07   5245.030608  0.996244
5              ElasticNet   5229.963587  3.721969e+07   6100.793940  0.994919
6                     KNN   4660.000000  3.939600e+07   6276.623296  0.994622
7           Decision Tree   5550.000000  7.235000e+07   8505.880319  0.990123
8  Hist Gradient Boosting   8496.810296  1.464407e+08  12101.268039  0.980009
9                     SVR  77191.494956  7.338903e+09  85667.400287 -0.001858

In [22]:
df = pd.read_csv("./regression_results.csv")
df

                    Model           MAE           MSE          RMSE        R2
0           Random Forest   2756.300000  1.060585e+07   3256.662509  0.998552
1       Gradient Boosting   2890.465480  1.362977e+07   3691.852299  0.998139
2       Linear Regression   3823.040913  2.459490e+07   4959.324048  0.996642
3                   Lasso   3823.104119  2.459608e+07   4959.443526  0.996642
4                   Ridge   4245.476426  2.751035e+07   5245.030608  0.996244
5              ElasticNet   5229.963587  3.721969e+07   6100.793940  0.994919
6                     KNN   4660.000000  3.939600e+07   6276.623296  0.994622
7           Decision Tree   5550.000000  7.235000e+07   8505.880319  0.990123
8  Hist Gradient Boosting   8496.810296  1.464407e+08  12101.268039  0.980009
9                     SVR  77191.494956  7.338903e+09  85667.400287 -0.001858

In [26]:
print(results)

[{'Model': 'Linear Regression', 'MAE': 3823.040912945688, 'MSE': 24594895.01210876, 'RMSE': 4959.324047902976, 'R2': 0.996642468078109}, {'Model': 'Ridge', 'MAE': 4245.476426146501, 'MSE': 27510346.07435423, 'RMSE': 5245.030607570773, 'R2': 0.9962444700381344}, {'Model': 'Lasso', 'MAE': 3823.1041190766105, 'MSE': 24596080.084891073, 'RMSE': 4959.443525728574, 'R2': 0.9966423062998337}, {'Model': 'ElasticNet', 'MAE': 5229.963586618995, 'MSE': 37219686.70234093, 'RMSE': 6100.793940327843, 'R2': 0.9949190152605097}, {'Model': 'Decision Tree', 'MAE': 5550.0, 'MSE': 72350000.0, 'RMSE': 8505.88031893231, 'R2': 0.9901232579187991}, {'Model': 'Random Forest', 'MAE': 2756.3, 'MSE': 10605850.7, 'RMSE': 3256.6625093798098, 'R2': 0.9985521596141587}, {'Model': 'Gradient Boosting', 'MAE': 2890.4654802356745, 'MSE': 13629773.39564317, 'RMSE': 3691.8522987307024, 'R2': 0.9981393537463168}, {'Model': 'Hist Gradient Boosting', 'MAE': 8496.810296455995, 'MSE': 146440688.15927607, 'RMSE': 12101.26803931208, 'R2': 0.9800088886365896}, {'Model': 'SVR', 'MAE': 77191.49495601602, 'MSE': 7338903471.9622755, 'RMSE': 85667.40028717036, 'R2': -0.0018584208901319954}, {'Model': 'KNN', 'MAE': 4660.0, 'MSE': 39396000.0, 'RMSE': 6276.62329600877, 'R2': 0.9946219194052386}]