In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran"],
    "Age": [24, 25, 23, 26, 24],
    "Salary": [50000, 65000, 55000, 70000, 60000],
    "Branch": ["CSE", "ECE", "CSE", "ECE", "CSE"]
})
print(df)

    Name  Age  Salary Branch
0   Ravi   24   50000    CSE
1  Priya   25   65000    ECE
2   Arun   23   55000    CSE
3   Sita   26   70000    ECE
4  Kiran   24   60000    CSE

### **1. Selecting a Single Column**

In [5]:
df['Age']

0    24
1    25
2    23
3    26
4    24
Name: Age, dtype: int64

In [11]:
df['Age'].value_counts()

Age
24    2
25    1
23    1
26    1
Name: count, dtype: int64

### **2. Selecting Multiple Columns**

Why two brackets?
- The outer brackets are DataFrame indexing:   `df[ ... ]`
- The inner brackets create a Python list:   `["Name", "Age"]`

In [12]:
df[["Name", "Age"]]

    Name  Age
0   Ravi   24
1  Priya   25
2   Arun   23
3   Sita   26
4  Kiran   24

### **Single vs Multiple Columns**
- `df["Age"]` → Series
- `df[["Age"]]` → DataFrame

In [13]:
df[["Age"]]

   Age
0   24
1   25
2   23
3   26
4   24

In [15]:
print(type(df["Age"]), df["Age"].shape)
print(type(df[["Age"]]), df[["Age"]].shape)

<class 'pandas.Series'> (5,)
<class 'pandas.DataFrame'> (5, 1)

### **3. Selecting Columns Using Lists**

In [18]:
selected_columns = ["Name", "Salary"]
result = df[selected_columns]
print(result, type(result), sep='\n')

    Name  Salary
0   Ravi   50000
1  Priya   65000
2   Arun   55000
3   Sita   70000
4  Kiran   60000
<class 'pandas.DataFrame'>

### **4. Selecting Columns Dynamically**

In [27]:
# Give me the columns whose data is numeric.
numerical_columns = df.select_dtypes(include="number")
numerical_columns

   Age  Salary
0   24   50000
1   25   65000
2   23   55000
3   26   70000
4   24   60000

In [ ]:
# Give me the names of the columns that contain numeric data.
numerical_columns.columns

Index(['Age', 'Salary'], dtype='str')

### **Columns containing a word**

Suppose you have:
|columns|
|--|
math_score
science_score
english_score
age
name

In [ ]:
score_columns = [col for col in df.columns if "score" in col]
df[score_columns]

### **or filter()**

In [ ]:
score_columns = df.filter(like="score")