In [2]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Arun", "Sita", "Kiran"],
    "Age": [24, 25, 23, 26, 24],
    "Salary": [50000, 65000, 55000, 70000, 60000],
    "Branch": ["CSE", "ECE", "CSE", "ECE", "CSE"]
}, index=["A", "B", "C", "D", "E"])
df

    Name  Age  Salary Branch
A   Ravi   24   50000    CSE
B  Priya   25   65000    ECE
C   Arun   23   55000    CSE
D   Sita   26   70000    ECE
E  Kiran   24   60000    CSE

In [14]:
df.iloc[[-3,-2],[1, 2] ]

   Age  Salary
C   23   55000
D   26   70000

### **Specific Rows and Columns**

`df.loc[rows, columns]`

`df.iloc[rows, columns]`

In [4]:
df.loc[["B", "D"], ["Name", "Salary"]]
df.iloc[[0, 2], [0, 2]]

   Name  Salary
A  Ravi   50000
C  Arun   55000

### **Selecting Ranges**

In [ ]:
df.iloc[0:3]
df.iloc[0:3, 0:2]